name: Masscan and ShuffleDNS Installation

on: [push]

jobs:
  install-tools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
        

    - name: executing FUZZ
      run: |
        cargo install x8
        curl -s https://wordlists-cdn.assetnote.io/data/manual/wordlist_with_underscores.txt > wlist2.txt
        x8 -u "https://pmg-acg-users.verisign.com/heartbeat/" -w wlist2.txt -X GET -o result
        
    - name: Upload output as artifact
      uses: actions/upload-artifact@v2
      with:
        name: command-output
        path: result
