name: Masscan and ShuffleDNS Installation

on: [push]

jobs:
  install-tools:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21   

    - name: executing FUZZ
      run: |
        git clone https://github.com/sh1yo/x8
        cd x8
        cargo update
        cargo build --release
        cp ./target/release/x8 /usr/local/bin 
        sudo apt-get -y install crunch
        crunch 1 4 abcdefghijklmnopqrstuvwxyz1234567890-_ > 0to4chars.txt
        curl -s https://wordlists-cdn.assetnote.io/data/manual/wordlist_with_underscores.txt > wlist2.txt
        cat wlist2.txt 0to4chars.txt | sort -u > all_words.txt
        x8 -u "http://63.140.38.210/optout" -w all_words.txt -X GET
        
    - name: Upload output as artifact
      uses: actions/upload-artifact@v2
      with:
        name: command-output
        path: result
